python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json
python train.py -c configs/train_propainter.json